export const UPLOAD_FILE_IMAGE_REQUEST = "UPLOAD_FILE_IMAGE_REQUEST";
export const UPLOAD_FILE_IMAGE_SUCCESS = "UPLOAD_FILE_IMAGE_SUCCESS";
export const UPLOAD_FILE_IMAGE_FAIL = "UPLOAD_FILE_IMAGE_FAIL";
export const UPLOAD_FILE_IMAGE_ERROR = "UPLOAD_FILE_IMAGE_PRODUCT_ERROR";
// Image Product
export const UPLOAD_FILE_IMAGE_PRODUCT_REQUEST = "UPLOAD_FILE_IMAGE_PRODUCT_REQUEST";
export const UPLOAD_FILE_IMAGE_PRODUCT_SUCCESS = "UPLOAD_FILE_IMAGE_PRODUCT_SUCCESS";
export const UPLOAD_FILE_IMAGE_PRODUCT_FAIL = "UPLOAD_FILE_IMAGE_PRODUCT_FAIL";
export const UPLOAD_FILE_IMAGE_PRODUCT_ERROR = "UPLOAD_FILE_IMAGE_PRODUCT_ERROR";